Profile Redesign
FleetAdmiralJakob/chat-io pull request #232
Opened 2024-06-15 22:16 UTC by Gamius00

- New UI

2024-06-18 16:44 UTC, FleetAdmiralJakob requested changes

2024-06-18 16:44 UTC, FleetAdmiralJakob commented on package.json
> +    "zod": "3.24.0-canary.20240523T174819"
Dont switch to canary without a reason

2024-06-18 16:48 UTC, FleetAdmiralJakob requested changes

2024-06-18 16:48 UTC, FleetAdmiralJakob commented on src/app/(auth)/sign-up/signup-form.tsx
> +                a Email
```suggestion
                a email
```
Typo

2024-07-07 02:58 UTC, FleetAdmiralJakob commented on src/app/(auth)/sign-up/signup-form.tsx
> +                a Email
```suggestion
                an email.
```

2024-07-07 03:01 UTC, FleetAdmiralJakob commented on src/app/(auth)/sign-up/signup-form.tsx
> +                a Email
```suggestion
                This is optional, but if you forgot your password, we can send you
                an email.
```

2024-07-11 00:44 UTC, Gamius00 commented on convex/chats.ts
> +        email: identity.email,
Set the value of the emailfield

2024-07-11 00:44 UTC, Gamius00 commented on convex/messages.ts
> +export const createDeleteRequest = mutation({
This is the mutation for creating a delete all messages request

2024-07-11 00:44 UTC, Gamius00 commented on convex/messages.ts
> +export const deleteAllMessagesInChat = mutation({
This is the mutation for delete all messages

2024-07-11 00:44 UTC, Gamius00 commented on convex/messages.ts
> +export const rejectRequest = mutation({
This is the reject request mutation

2024-07-11 00:44 UTC, Gamius00 commented on convex/schema.ts
> +    .field("type", v.string(), { default: "message" })
This is the type of a message. 
I need a difference between the normal messages and the request messages

2024-07-11 00:44 UTC, Gamius00 commented on convex/users.ts
> +export const updateUserData = mutation({
Here I update the user data (firstname, lastname, email)

2024-07-11 00:44 UTC, Gamius00 commented on src/app/(internal-sites)/chats/[chatId]/page.tsx
> +        type: "message",
This is the normal type of any message that is not a request

2024-07-11 00:44 UTC, Gamius00 commented on src/app/(internal-sites)/profile/page.tsx
> +        <p className="my-10 text-xl font-bold sm:text-2xl">Profile</p>
This is only the profilepage

2024-07-11 00:44 UTC, Gamius00 commented on src/app/api/sign-up/route.ts
> +        if (
Added a email error

2024-07-11 00:44 UTC, Gamius00 commented on src/components/message.tsx
> +              ) : message.type != "message" ? (
Added the UI of the delete messages request

2024-07-11 00:44 UTC, Gamius00 commented on tailwind.config.ts
> +        accept: "#00834C",
Added new color for the accept button

2024-07-11 03:35 UTC, FleetAdmiralJakob requested changes

2024-07-11 03:35 UTC, FleetAdmiralJakob commented on package.json
> +    "zod": "3.23.8"
Make it as it was before (^^^^^^)

2024-07-11 03:42 UTC, FleetAdmiralJakob approved these changes

2024-07-11 03:42 UTC, FleetAdmiralJakob commented on src/components/password-dialog.tsx
Whats this file doing? Why not use the same dialog as for the add user dialog?

2024-08-01 23:51 UTC, FleetAdmiralJakob approved these changes

2024-08-01 23:51 UTC, FleetAdmiralJakob approved these changes

2024-08-02 07:45 UTC, merged